# Putting the "fun" back in fundraising {#optimizing-fundraising-efforts}

#### Keywords

philanthropy; fundraising; university; nonprofit; development; donor

## Increasing philanthropy without increasing expenditures
Philanthropy and funraising are key to survival for non-profit organizations, particularly universities. Federal and state government support goes primarily to public universities^1^, but almost 20%^2^ of college students attend private universities. These universities must rely more heavily on philanthropy to support project-based endeavors, special interest groups, upgrading/repairing facilities, and most importantly, scholarships to supplement income from tuition and grants. As the need for funding increases, resources to achieve it stagnate. Therefore, fundraising and development team must strive for the perfect balance of minimizing cost to fundraise (personnel, venues, food, goods, etc.) while increasing giving (amount, frequency, and reach).

Achieving this lofty goal requires a sophisticated approach to optimizing marketing and outreach campaigns. Luckily, universities collect a lot of data on donors, which is increasingly easier in this day and age, but most don’t know what to do with it. This is where we come in – we can help your university better utilize donor data to increase fundraising capabilities while decreasing cost. 


## Philanthropy optimization made easy
Our software tool, FUNdraiser, goes beyond current approaches that focus primarily on descriptive statistics and analysis from email marketing, donations, and events. It easily imports existing data about donor demographic information, giving history, and online and in-person engagement. FUNdraiser then develops an algorithm based that is used to build a predictive model for a particular donor’s (or group of donors’) likelihood to give. The process is iterative: FUNdraiser integrates with email, donation tracking, and event registration platforms so it can easily gather new data to update its algorithm and identify strong predictors of giving over time. 

FUNdraiser also allows you to quickly segment data so you can create new campaigns and change the optimization goal with just the click of a button. This way, you can monitor multiple campaigns, from increasing philanthropic engagement by recent alumni to maximizing gifts over $1,000,000.

In FUNdraiser, results are clearly displayed using state-of-the-art data visualization tools that can be easily understood by all interested parties, such as development officers, board members, and CEOs. Our comprehensive fundraising support system also offers one-on-one consulting for how to use these results for annual and long-term planning, large- and small-scale budgeting, and short-term prediction for smaller campaigns and outreach.


## To millions and beyond
Our comprehensive fundraising support system also offers one-on-one consulting for how to use these results for annual and long-term planning, large- and small-scale budgeting, and short-term prediction for smaller campaigns and outreach. 

However, many seasoned fundraising professionals will claim that fundraising is an “art and a science,” and while I firmly believe that there’s more science to it than you think, there is still the art of personal outreach and building connections, which drive engagement, which is ultimately reflected in the data. 

It is also important to keep in mind is that just because a particular factor is less of a predictor, or a certain group is less likely to give, this doesn’t mean you should ignore them. In fact, you should question, “Why isn’t this group as likely to give? What can we do to increase that likelihood?” and re-focus efforts on increasing giving in those groups.

Correctly using the insights gathered using FUNdraiser can result in huge financial gains for your university. This allows more students to attend college through the support of financial aid, provides students an enhanced educational experience with increased resources, facilitates success for them in their further education and career, all of which ultimately drive interest and prestige for your university.

## Bibliography

1. http://www.pewtrusts.org/en/research-and-analysis/issue-briefs/2015/06/federal-and-state-funding-of-higher-education
2. https://www.usnews.com/education/blogs/the-college-solution/2011/09/06/20-surprising-higher-education-facts
